Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
 
  config.vm.define "test_host" do |test_host|
    test_host.vm.hostname = "test-host"
    test_host.vm.network "private_network", ip: "192.168.5.13"
  end

  config.vm.define "jwt_server" do |jwt_server|
    jwt_server.vm.hostname = "jwt-server"
    jwt_server.vm.network "private_network", ip: "192.168.5.12"
  end

  config.vm.define "emqx" do |emqx|
    emqx.vm.hostname = "emqx"
    emqx.vm.network "private_network", ip: "192.168.5.11"
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "hosts"
  end
end
